Update golangci-lint version from v1.55.2 to v1.58.0
This is necessary to merge https://github.com/pulumi/pulumi-tailscale/pull/408, since
before we were seeing spurious lint errors:

```
 Running [/home/runner/golangci-lint-1.55.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=provider] in [/home/runner/work/pulumi-tailscale/pulumi-tailscale/provider] ...
  Error: cannot range over addrs.Len() (value of type int) (typecheck)
  Error: cannot range over rr.Len() (value of type int) (typecheck)
  Error: cannot range over rr.Len() (value of type int) (typecheck)
  Error: cannot range over in.Len() (value of type int) (typecheck)

  Error: issues found
```

https://github.com/pulumi/pulumi-tailscale/actions/runs/8946537237/job/24577325007?pr=408
shows that this change runs as expected.