Use GITHUB_TOKEN when setting up mise in native providers (#1833)
I noticed a job get throttled while fetching plugins since it's using
anonymous access.

```
  mise ERROR Failed to install tools: vfox-pulumi:pulumi/pulumi-std@latest, vfox-pulumi:pulumi/pulumi-converter-terraform@latest
  
  vfox-pulumi:pulumi/pulumi-std@latest: 
     0: Backend install method failed
     1: runtime error: Command failed with status exit status: 255: [resource plugin std-2.2.0] installing
        E1113 23:19:47.169794    2460 plugins.go:598] GitHub rate limit exceeded for https://api.github.com/repos/pulumi/pulumi-std/releases/tags/v2.2.0, try again in 20m0.830215302s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.
        error: [resource plugin std-2.2.0] downloading from : failed to download plugin: std-2.2.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-std-v2.2.0-linux-amd64.tar.gz
```

Including the action's short-lived GITHUB_TOKEN should be enough to
prevent this.

Normally the token is used automatically, but native providers use a
composite action which needs it to be passed explicitly.