Deploy infra as part of the merge queue (#2059)
We deploy https://app.pulumi.com/pulumi/pulumi-provider-repos/production
from this repo but it happens as a post-commit hook, so failures tend to
go unnoticed.

For example we most recently failed to deploy due to some repos being
archived:

```
Diagnostics:
github:index:BranchProtection (wavefront-default):
error: sdk-v2/provider2.go:572: sdk.helper_schema: Repository is archived: provider=github@6.10.1
error: deleting urn:pulumi:production::pulumi-provider-repos::github:index/branchProtection:BranchProtection::wavefront-default: 1 error occurred:
* Repository is archived
pulumi:pulumi:Stack (pulumi-provider-repos-production):
error: update failed
github:index:BranchProtection (sumologic-default):
error: sdk-v2/provider2.go:572: sdk.helper_schema: Repository is archived: provider=github@6.10.1
error: deleting urn:pulumi:production::pulumi-provider-repos::github:index/branchProtection:BranchProtection::sumologic-default: 1 error occurred:
* Repository is archived
```

We were also using an expired token for who-knows-how-long
https://github.com/pulumi/ci-mgmt/pull/2012.

This updates our stack as part of the merge queue, so "this code
deploys" becomes a precondition for committing.