Fix checking out upstream without patches (#1193)
Allow the wildcard listing operations to return zero results instead of
failing with:

```
error: can't open patch '../patches/*.patch': No such file or directory

Failed to apply *.patch.
```